name: Bridger

exclude: ["README.md", "public", "Bridger Creative.tmproj", "Gemfile", "Gemfile.lock", "libs", "assets", "vendor", "s3_config.yml"]
gems: [oembed]
keep_files:  ['.git']
timezone: America/New_York
encoding: UTF-8
safe: false

paginate: 5
paginate_path: "blog/page:num"

url: http://www.bridgercreative.com
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
category_dir: /blog/categories/
future: false

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Twitter
twitter_user: bridgercreative
twitter_tweet_button: true
twitter_timeline: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Disqus Comments
disqus_short_name: bridgercreative
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-195847-4

# Facebook Like
facebook_user: studiobridger
facebook_like_button: true
facebook_facepile: true

embedly_api_key: 29005326497c4f8e82cfd8645d77aaf9

# Image thumbnail generator
image:
  source: assets/site_images/
  output: img
  presets: # Predefined sizes go here
    post: 
      width: 622
      height: AUTO