name: Bridger

exclude: ["README.md", "public", "Bridger Creative.tmproj", "Gemfile", "Gemfile.lock", "libs", "assets", "vendor", "s3_config.yml"]
gems: [oembed]
keep_files:  ['.git']
timezone: America/New_York
encoding: UTF-8
safe: false

paginate: 5
paginate_path: "blog/page:num"

url: http://www.bridgercreative.com
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
category_dir: /blog/categories/
future: false

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


project_categories: &project_categories
- Brand Identity
- Branding
- Environmental
- Packaging
- Publication
- UX/UI
- User Experience
- User Interface
- Design
- Video & Motion
- Visual Strategy
- Visual Systems


post_categories: &post_categories
- Information Architecture
- Publication
- Ux/Ui
- Brand Identity
- Visual Systems
- Blog
- Infographics & Data Visualization
  
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Twitter
twitter_user: bridgercreative
twitter_tweet_button: true
twitter_timeline: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Disqus Comments
disqus_short_name: bridgercreative
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-195847-4

# Facebook Like
facebook_user: studiobridger
facebook_like_button: true
facebook_facepile: true

embedly_api_key: 29005326497c4f8e82cfd8645d77aaf9

# Image thumbnail generator
image:
  source: assets/site_images/
  output: img
  presets: # Predefined sizes go here
    post: 
      width: 622
      height: AUTO

prose:
  siteurl: "http://www.bridgercreative.com.s3-website-us-east-1.amazonaws.com"
  metadata:
    _posts:
      - name: "layout"
        field:
          value: "post"
          label: Layout
      - name: "date"
        field: 
          value: CURRENT_DATE
          label: Date
      - name: "published"
        field: 
          element: button
          on: true
          off: false
          label: Publish
      - name: "published"
        field: 
          element: button
          on: true
          off: false
          label: Publish
      - name: "categories"
        field:
          element: "multiselect"
          label: "Select Categories"
          options: *post_categories
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          options: ""
          alterable: true

    _projects:
      - name: "layout"
        field:
          value: "project"
          label: Layout
      - name: "date"
        field: 
          value: CURRENT_DATE
          label: Date
      - name: "published"
        field: 
          element: button
          on: true
          off: false
          label: Publish
      - name: "categories"
        field:
          element: "multiselect"
          label: "Select Categories"
          options: *project_categories
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          options: ""
          alterable: true
